name: Release

on:
  push:
    branches: [master, main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo under GH workspace
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: Lint and test
        run: yarn run lint && yarn run test

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_PUBLISH }}
